//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acheiv
    {
        public int Id { get; set; }
        public string acheiv_name { get; set; }
        public string pic { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string remark { get; set; }
    }
}
