//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONATION
    {
        public int Id { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> cat_id { get; set; }
        public Nullable<int> use_id { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual User User { get; set; }
    }
}
